OR: "or"
AND: "and"
NOT: "not"
TRUE: "True"
FALSE: "False"
LNAME: /[_A-Za-z](\w+|-)*/
//LNAME: ("_"|LETTER) ("_"|"-"|LETTER|DIGIT)* ("_"|LETTER|DIGIT)*

?start: element
element: clause | atomic | negated_atomic
atomic: fact | symbol | bool
symbol: "?" CNAME
negated_atomic: "(" NOT atomic ")"
fact: "(" LNAME CNAME* ")"
bool: TRUE -> bool_true
    | FALSE -> bool_false

clause: conjunction | disjunction | negation
disjunction: "(" OR element* ")"
conjunction: "(" AND element* ")"
//negation: "(not" clause ")"
negation: "(" NOT (clause | negated_atomic) ")"


%import common.WS
%import common.CNAME
%import common.LETTER
%import common.DIGIT
%ignore WS
