TRIPLE_STRING: /('{3}([^\\]|\\.|\\n)*?'{3})|("{3}([^\\]|\\.|\\n)*?"{3})/
SINGLE_STRING:  /'([^'\\]|\\.)*'|\"([^\"\\]|\\.)*\"/

?start: tool_call
tool_call: function_name "(" [kwarg ("," kwarg)*] ")"
kwarg: arg_name "=" arg_val
arg_name: CNAME
arg_val: primitive
function_name: CNAME
primitive: FLOAT -> float
         | INT -> int
         | TRIPLE_STRING -> triple_string
         | SINGLE_STRING -> string


%import common.FLOAT
%import common.LETTER
%import common.INT
%import common.WS
%import common.CNAME
%ignore WS
